package gay.mountainspring.cauldronsplus_sswplus.client;

import gay.mountainspring.cauldronsplus_sswplus.block.CSSWPBlocks;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.util.DyeColor;

public class CSSWPClient implements ClientModInitializer {
	@Override
	public void onInitializeClient() {
BlockRenderLayerMap renderLayerMap = BlockRenderLayerMap.INSTANCE;
		
		renderLayerMap.putBlocks(RenderLayer.getTranslucent(),
				CSSWPBlocks.GOLD_HONEY_CAULDRON,
				CSSWPBlocks.GOLD_SLIME_CAULDRON,
				CSSWPBlocks.NETHERITE_HONEY_CAULDRON,
				CSSWPBlocks.NETHERITE_SLIME_CAULDRON,
				CSSWPBlocks.COPPER_HONEY_CAULDRON,
				CSSWPBlocks.COPPER_SLIME_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_SLIME_CAULDRON);
		
		var blockColorRegistry = ColorProviderRegistry.BLOCK;
		
		blockColorRegistry.register((state, world, pos, tintIndex) -> world != null && pos != null && world.getBlockEntityRenderData(pos) instanceof Integer i ? i : -1,
				CSSWPBlocks.GOLD_DYED_WATER_CAULDRON,
				CSSWPBlocks.GOLD_POTION_CAULDRON,
				CSSWPBlocks.NETHERITE_DYED_WATER_CAULDRON,
				CSSWPBlocks.NETHERITE_POTION_CAULDRON,
				CSSWPBlocks.COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.COPPER_POTION_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_POTION_CAULDRON);
		
		blockColorRegistry.register((state, world, pos, tintIndex) -> DyeColor.WHITE.getEntityColor(),
				CSSWPBlocks.GOLD_MILK_CAULDRON,
				CSSWPBlocks.NETHERITE_MILK_CAULDRON,
				CSSWPBlocks.COPPER_MILK_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_MILK_CAULDRON);
	}
}