package gay.mountainspring.cauldronsplus_sswplus.datagen;

import java.util.concurrent.CompletableFuture;

import gay.mountainspring.cauldronsplus_sswplus.block.CSSWPBlocks;
import gay.mountainspring.sswplus.tag.SSWPTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider.BlockTagProvider;
import net.minecraft.registry.RegistryWrapper.WrapperLookup;

public class CSSWPBlockTagGen extends BlockTagProvider {
	public CSSWPBlockTagGen(FabricDataOutput output, CompletableFuture<WrapperLookup> registriesFuture) {
		super(output, registriesFuture);
	}
	
	@Override
	protected void configure(WrapperLookup wrapperLookup) {
		this.getOrCreateTagBuilder(SSWPTags.Blocks.UNWAXED_COPPER_CAULDRONS)
		.add(CSSWPBlocks.COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.COPPER_POTION_CAULDRON,
				CSSWPBlocks.COPPER_MILK_CAULDRON,
				CSSWPBlocks.COPPER_HONEY_CAULDRON,
				CSSWPBlocks.COPPER_SLIME_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.EXPOSED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WEATHERED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.OXIDIZED_COPPER_SLIME_CAULDRON);
		
		this.getOrCreateTagBuilder(SSWPTags.Blocks.WAXED_COPPER_CAULDRONS)
		.add(CSSWPBlocks.WAXED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_EXPOSED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_WEATHERED_COPPER_SLIME_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_DYED_WATER_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_POTION_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_MILK_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_HONEY_CAULDRON,
				CSSWPBlocks.WAXED_OXIDIZED_COPPER_SLIME_CAULDRON);
	}
}